---
device:
    qubit:
        T1:
        - 393.0070389378491
        f_ge:
        - 3562.6105332943075
        f_ef:
        - 3419.036012060942
        ramp_sigma:
        - 0.005
        ramp_sigma_num:
        - 3.0
        pulses:
            pi_ge:
                gain:
                - 3289
                sigma:
                - 0.035
                length:
                - 0.0
                type:
                - gauss
            hpi_ge:
                gain:
                - 1629
                length:
                - 0.0
                sigma:
                - 0.035
                type:
                - gauss
            pi_ef:
                gain:
                - 3038
                length:
                - 0.0
                sigma:
                - 0.035
                type:
                - gauss
            hpi_ef:
                gain:
                - 1514
                sigma:
                - 0.035
                type:
                - gauss
            slow_pi_ge:
                gain:
                - 15
                sigma:
                - 0.1
                length:
                - 10
                type:
                - flat_top
        T1_ef:
        - 192.7916396799921
    readout:
        trig_offset:
        - 450
        frequency:
        - 749.4328673317561
        gain:
        - 800
        phase:
        - 90.69547931076305
        threshold:
        - -35.01108625176434
        threshold_list:
        -   - -35.01108625176434
        man1_drive_list:
        - 0.0
        man2_drive_list:
        - 0.0
        readout_length:
        - 1.5
        relax_delay:
        - 2500
        confusion_matrix_with_reset:
        - 0.9964530022802125
        - 0.0035469977197875036
        - 0.013768302080657598
        - 0.9862316979193424
        confusion_matrix_without_reset:
        - 0.9792000000000001
        - 0.02079999999999993
        - 0.043408681736347245
        - 0.9565913182636527
        Ie:
        - 23.201754387107762
        Ig:
        - -93.975256059321
        confusion_matrix_with_active_reset:
        - 0.994087665647299
        - 0.005912334352700999
        - 0.010668855149774321
        - 0.9893311448502257
    manipulate:
        f_ge:
        - 4979.50248109926
        - 5157.8527963217475
        displace_sigma:
        - 0.05
        - 0.05
        revival_time:
        - 1.6421546981290847
        - 1.7366205852286094
        revival_stark_shift:
        - -1.174907477401628
        - -2.6792227141937364
        gain_to_alpha:
        - 0.000672367126208473
        - 0.00020045
        freq_to_alpha:
        - 0.495062203431879
        - 0.0
        alpha_scale:
        - 1.0
        - 1.0
        chi_ge:
        - 0.2802173281623599
        chi_ef:
        - 1.2311804927283654
        ramp_sigma: 0.005
    storage:
        storage_man_file: man1_storage_swap_dataset.csv
        idling_phase:
        -   - -52.6696123
            - -22.7088024
            - 4.32404839
            - 1.74059096
            - 3.07928552
            - 131.15854816947694
            - -90.34878087129891
        -   - -0.8543699
            - -116.043431
            - 3.45837055
            - 0.608331428
            - -2.036
            - 9.45
            - 95.59156092221656
        -   - 1.04040701
            - -3.74923237
            - -117.783814
            - 0.356992259
            - -2.45519509
            - 0.647967825
            - 12.8401564
        -   - 1.66740192
            - -4.21812224
            - 3.29786448
            - -154.122273
            - -1.60291285
            - -1.18402153
            - 5.044314
        -   - 4.82521854
            - 0.209877344
            - 5.59148305
            - 7.67963852
            - -91.167355
            - 1.30630108
            - 5.65421906
        -   - 3.70780701
            - 0.0768208841
            - 4.16044796
            - 2.61829414
            - 3.48690085
            - -37.3968965
            - 4.05643677
        -   - 3.84028579
            - -0.418792628
            - 4.0522379
            - 3.24634888
            - 2.06016015
            - 3.24251258
            - -22.4708301
        idling_freq:
        - -2.5937677197135596
        - -2.85371864950844
        - -2.446015004544113
        - -1.8393250164457633
        - -3.231025833205897
        - -3.2053137013077597
        - -2.935087792327744
        ramp_sigma: 0.005
        floquet_man_stor_file: floquet_storage_swap_dataset.csv
    active_reset:
        qubit_ge:
        - 4000
        - 0.1422665780546079
        - 0.005
        qubit_ef:
        - 3000
        - 0.15377089082752435
        - 0.005
        relax_delay:
        - 50.0
        M_lossy:
        -   - 2312.9
            - 5000.0
            - 10.0
            - 2.0
            - 2.0
        -   - 2094.05
            - 8000.0
            - 15.0
            - 2.0
            - 2.0
    multiphoton_config:
        file: multiphoton_config.yml
    multiphoton:
        pi:
            gn-en:
                frequency:
                - 3562.5885072817487
                - 3569.859305862891
                - 3571.543042357372
                - 3571.299620008302
                gain:
                - 3319
                - 3511
                - 3449
                - 3430
                length:
                - 0
                - 0
                - 0
                - 0
                sigma:
                - 0.035
                - 0.035
                - 0.035
                - 0.035
                type:
                - gauss
                - gauss
                - gauss
                - gauss
            en-fn:
                frequency:
                - 3419.01692885307
                - 3426.3209219320834
                - 3427.712094472353
                - 3427.4772366132443
                gain:
                - 3074
                - 2907
                - 2763
                - 2768
                length:
                - 0
                - 0
                - 0
                - 0
                sigma:
                - 0.035
                - 0.035
                - 0.035
                - 0.035
                type:
                - gauss
                - gauss
                - gauss
                - gauss
            fn-gn+1:
                frequency:
                - 1998.6868657264545
                - 2013.0267717275865
                - 2010.595323987349
                - 2010.07793195468
                gain:
                - 8000
                - 8000
                - 8000
                - 8000
                length:
                - 0.5895751414942867
                - 0.4138889877632088
                - 0.31584821479967073
                - 0.26838059127779085
                sigma:
                - 0.005
                - 0.005
                - 0.005
                - 0.005
                type:
                - flat_top
                - flat_top
                - flat_top
                - flat_top
        hpi:
            gn-en:
                frequency:
                - 3570.8903758017664
                - 3570.0567055299525
                - 3567.7644237298246
                - 3565.49698806312
                gain:
                - 8963
                - 1689
                - 1689
                - 1697
                length:
                - 0
                - 0
                - 0
                - 0
                sigma:
                - 0.007
                - 0.035
                - 0.035
                - 0.035
                type:
                - gauss
                - gauss
                - gauss
                - gauss
            en-fn:
                frequency:
                - 0
                - 0
                - 0
                - 0
                gain:
                - 0
                - 0
                - 0
                - 0
                length:
                - 0
                - 0
                - 0
                - 0
                sigma:
                - 0.035
                - 0.035
                - 0.035
                - 0.035
                type:
                - gauss
                - gauss
                - gauss
                - gauss
    optimal_control:
        fock:
            '1':
                frequency:
                - 3569.7141623787825
                - 4979.505867743005
                gain:
                - 1407
                - 1715
                phase:
                - 0.0
                - 0.0
                filename: H:\Shared drives\SLab\Multimode\optimal_control\pulse_fock_1.npz
            '2':
                frequency:
                - 3569.7141623787825
                - 4979.505867743005
                gain:
                - 2141
                - 2421
                phase:
                - 0.0
                - 0.0
                filename: H:\Shared drives\SLab\Multimode\optimal_control\pulse_fock_2.npz
            0+2:
                frequency:
                - 3569.7028312412162
                - 5013.871083295973
                gain:
                - 10
                - 10
                phase:
                - 0.0
                - 0.0
                filename: H:\Shared drives\SLab\Multimode\optimal_control\pulse_fock_0+2.npz
            0+2i:
                frequency:
                - 3569.7141623787825
                - 4979.505867743005
                gain:
                - 867
                - 2452
                phase:
                - 0.0
                - 0.0
                filename: H:\Shared drives\SLab\Multimode\optimal_control\pulse_fock_0+2i.npz
            0+4:
                frequency:
                - 3569.7141623787825
                - 4979.505867743005
                gain:
                - 1204
                - 2701
                phase:
                - 0.0
                - 0.0
                filename: H:\Shared drives\SLab\Multimode\optimal_control\pulse_fock_0+4.npz
            encode:
                frequency:
                - 3569.7028312412162
                - 5013.871083295973
                gain:
                - 10
                - 10
                phase:
                - 0.0
                - 0.0
                filename: H:\Shared drives\SLab\Multimode\optimal_control\pulse_fock_encode.npz
            decode:
                frequency:
                - 3569.7028312412162
                - 5013.871083295973
                gain:
                - 10
                - 10
                phase:
                - 0.0
                - 0.0
                filename: H:\Shared drives\SLab\Multimode\optimal_control\pulse_fock_decode.npz
        GKP:
            Z:
                frequency:
                - 3569.7028312412162
                - 5013.871083295973
                gain:
                - 10
                - 10
                phase:
                - 0.0
                - 0.0
                filename: H:\Shared drives\SLab\Multimode\optimal_control\pulse_GKP_Z.npz
        test:
            '1':
                frequency:
                - 3569.7141623787825
                - 4979.505867743005
                gain:
                - 2995
                - 4002
                phase:
                - 0.0
                - 0.0
                filename: H:\Shared drives\SLab\Multimode\optimal_control\test.npz
            '2':
                frequency:
                - 3569.7028312412162
                - 5013.871083295973
                gain:
                - 850
                - 2413
                phase:
                - 0.0
                - 0.0
                filename: H:\Shared drives\SLab\Multimode\optimal_control\test_pi.npz
hw:
    soc:
        dacs:
            qubit:
                ch:
                - 2
                type:
                - full
                nyquist:
                - 1
            readout:
                ch:
                - 5
                type:
                - full
                nyquist:
                - 1
            manipulate_in:
                ch:
                - 3
                type:
                - full
                nyquist:
                - 2
            storage_in:
                ch:
                - 6
                type:
                - full
                nyquist:
                - 2
            flux_low:
                ch:
                - 1
                type:
                - full
                nyquist:
                - 1
            flux_high:
                ch:
                - 1
                type:
                - full
                nyquist:
                - 1
            sideband:
                ch:
                - 0
                type:
                - full
                nyquist:
                - 1
        adcs:
            readout:
                ch:
                - 0
            cavity_out:
                ch:
                - 1
aliases:
    soc: Qick101
data_management:
    output_root: D:/experiments
